### ISSUE TITLE
[Bug]Plexus 2.2.3 not clearing trackers/indicators after the buffs end

### ISSUE THREAD

**Issue by voozul** [doadin/Plexus#64] opened 2022-10-27 15:45 UTC
**Describe the bug**
Using the various indicator trackers (in the corners) the trackers show up correctly but don't clear when the spell ends (for example, if I cast renew I have a tracker showing it on my target in the bottom left corner but when the renew buff ends the tracker stays on plexus. This happens with many spells eg renew, power word shield, prayer of mending, atonement

**Comment by tiff79** [comment] 2022-10-27 15:56
doesn't always happen and not yet sure wot causes it.

**Comment by tiff79** [comment] 2022-10-27 16:06
reload ui clears the issue until its next triggered. Seems to be consistently reproducible by appying a buff that's tracked and portaling while the buff/indicator is still active..
So apply renew - take a portal (loading screen type, not oribos swap floor type).. and then waiting for buff to end AND manually removing the buff both leave the buff tracker remaining on.

**Comment by voozul** [comment] 2022-10-27 16:21
There also seems an issue with some buffs eg praye rof mending, atonement) being dropped by blizzard when you portal (ie if you portal with a 15 sec duration atonement and come out in 3 sec of loading the blizz buff of atonement is gone). No idea what is going on. Hope this info helps.

**Comment by doadin** [comment] 2023-03-11 01:24
Let me know if you still have issues but closing this as I think its solved and old.

**Closed by doadin** 2023-03-11 01:24 UTC
Labels: bug
